# Generated by Django 4.1.1 on 2022-09-10 00:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tweet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(default=uuid.uuid4)),
                ("text", models.CharField(max_length=250)),
                ("likes", models.IntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
